export const allUsers = [
  {
    id: '1',
    createdAt: '1',
    email: 'user1@example.com',
    fullName: 'User One',
    status: 'active',
  },
  {
    id: '2',
    createdAt: '2',
    email: 'user2@example.com',
    fullName: 'User Two',
    status: 'active',
  },
  {
    id: '3',
    createdAt: '3',
    email: 'user3@example.com',
    fullName: 'User Three',
    status: 'active',
  },
  {
    id: '4',
    createdAt: '4',
    email: 'user4@example.com',
    fullName: 'User Four',
    status: 'active',
  },
  {
    id: '5',
    createdAt: '5',
    email: 'user5@example.com',
    fullName: 'User Five',
    status: 'active',
  },
  {
    id: '6',
    createdAt: '6',
    email: 'user6@example.com',
    fullName: 'User Six',
    status: 'active',
  },
  {
    id: '7',
    createdAt: '7',
    email: 'user7@example.com',
    fullName: 'User Seven',
    status: 'active',
  },
  {
    id: '8',
    createdAt: '8',
    email: 'user8@example.com',
    fullName: 'User Eight',
    status: 'active',
  },
  {
    id: '9',
    createdAt: '9',
    email: 'user9@example.com',
    fullName: 'User Nine',
    status: 'active',
  },
  {
    id: '10',
    createdAt: '10',
    email: 'user10@example.com',
    fullName: 'User Ten',
    status: 'active',
  },
  {
    id: '11',
    createdAt: '11',
    email: 'user11@example.com',
    fullName: 'User Eleven',
    status: 'active',
  },
  {
    id: '12',
    createdAt: '12',
    email: 'user12@example.com',
    fullName: 'User Twelve',
    status: 'active',
  },
  {
    id: '13',
    createdAt: '13',
    email: 'user13@example.com',
    fullName: 'User Thirteen',
    status: 'active',
  },
  {
    id: '14',
    createdAt: '14',
    email: 'user14@example.com',
    fullName: 'User Fourteen',
    status: 'active',
  },
  {
    id: '15',
    createdAt: '15',
    email: 'user15@example.com',
    fullName: 'User Fifteen',
    status: 'active',
  },
  {
    id: '16',
    createdAt: '16',
    email: 'user16@example.com',
    fullName: 'User Sixteen',
    status: 'active',
  },
  {
    id: '17',
    createdAt: '17',
    email: 'user17@example.com',
    fullName: 'User Seventeen',
    status: 'active',
  },
  {
    id: '18',
    createdAt: '18',
    email: 'user18@example.com',
    fullName: 'User Eighteen',
    status: 'active',
  },
  {
    id: '19',
    createdAt: '19',
    email: 'user19@example.com',
    fullName: 'User Nineteen',
    status: 'active',
  },
  {
    id: '20',
    createdAt: '20',
    email: 'user20@example.com',
    fullName: 'User Twenty',
    status: 'active',
  },
  {
    id: '21',
    createdAt: '21',
    email: 'user21@example.com',
    fullName: 'User Twenty-One',
    status: 'active',
  },
  {
    id: '22',
    createdAt: '22',
    email: 'user22@example.com',
    fullName: 'User Twenty-Two',
    status: 'active',
  },
  {
    id: '23',
    createdAt: '23',
    email: 'user23@example.com',
    fullName: 'User Twenty-Three',
    status: 'active',
  },
  {
    id: '24',
    createdAt: '24',
    email: 'user24@example.com',
    fullName: 'User Twenty-Four',
    status: 'active',
  },
  {
    id: '25',
    createdAt: '25',
    email: 'user25@example.com',
    fullName: 'User Twenty-Five',
    status: 'active',
  },
  {
    id: '26',
    createdAt: '26',
    email: 'user26@example.com',
    fullName: 'User Twenty-Six',
    status: 'active',
  },
  {
    id: '27',
    createdAt: '27',
    email: 'user27@example.com',
    fullName: 'User Twenty-Seven',
    status: 'active',
  },
  {
    id: '28',
    createdAt: '28',
    email: 'user28@example.com',
    fullName: 'User Twenty-Eight',
    status: 'active',
  },
  {
    id: '29',
    createdAt: '29',
    email: 'user29@example.com',
    fullName: 'User Twenty-Nine',
    status: 'active',
  },
  {
    id: '30',
    createdAt: '30',
    email: 'user30@example.com',
    fullName: 'User Thirty',
    status: 'active',
  },
  {
    id: '31',
    createdAt: '31',
    email: 'user31@example.com',
    fullName: 'User Thirty-One',
    status: 'active',
  },
  {
    id: '32',
    createdAt: '32',
    email: 'user32@example.com',
    fullName: 'User Thirty-Two',
    status: 'active',
  },
  {
    id: '33',
    createdAt: '33',
    email: 'user33@example.com',
    fullName: 'User Thirty-Three',
    status: 'active',
  },
  {
    id: '34',
    createdAt: '34',
    email: 'user34@example.com',
    fullName: 'User Thirty-Four',
    status: 'active',
  },
  {
    id: '35',
    createdAt: '35',
    email: 'user35@example.com',
    fullName: 'User Thirty-Five',
    status: 'active',
  },
  {
    id: '36',
    createdAt: '36',
    email: 'user36@example.com',
    fullName: 'User Thirty-Six',
    status: 'active',
  },
  {
    id: '37',
    createdAt: '37',
    email: 'user37@example.com',
    fullName: 'User Thirty-Seven',
    status: 'active',
  },
  {
    id: '38',
    createdAt: '38',
    email: 'user38@example.com',
    fullName: 'User Thirty-Eight',
    status: 'active',
  },
  {
    id: '39',
    createdAt: '39',
    email: 'user39@example.com',
    fullName: 'User Thirty-Nine',
    status: 'active',
  },
  {
    id: '40',
    createdAt: '40',
    email: 'user40@example.com',
    fullName: 'User Forty',
    status: 'active',
  },
];
